// Bundles src/runner/index.ts into a single CJS string and writes it to
// convex/_runner/bundle.ts as `export const RUNNER_SOURCE: string = "..."`.
// Convex actions ship this string to a Daytona sandbox and execute it with node.
//
// Usage: node scripts/build-runner.mjs [--entry <path>] [--out <path>]
import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const entry = path.resolve(root, arg("--entry", "src/runner/index.ts"));
const out = path.resolve(root, arg("--out", "convex/_runner/bundle.ts"));

export async function buildRunner({ entryPoint = entry, outFile = out } = {}) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    write: false,
    platform: "node",
    target: "node20",
    format: "cjs",
    minify: false,
    sourcemap: false,
    legalComments: "none",
    logLevel: "warning",
    absWorkingDir: root,
    alias: {
      "@core": path.resolve(root, "src/core"),
      "@runtime": path.resolve(root, "src/runtime"),
    },
    define: { "process.env.NODE_ENV": '"production"' },
  });
  const code = result.outputFiles[0].text;
  const source = `// generated by scripts/build-runner.mjs — do not edit\nexport const RUNNER_SOURCE: string = ${JSON.stringify(code)};\n`;
  await mkdir(path.dirname(outFile), { recursive: true });
  await writeFile(outFile, source, "utf8");
  return { outFile, bundleBytes: Buffer.byteLength(code, "utf8"), fileBytes: Buffer.byteLength(source, "utf8") };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  buildRunner()
    .then(({ outFile, bundleBytes, fileBytes }) => {
      console.log(
        `runner bundle: ${(bundleBytes / 1024).toFixed(1)} KiB of JS -> ${path.relative(root, outFile)} (${(fileBytes / 1024).toFixed(1)} KiB)`,
      );
    })
    .catch((e) => {
      console.error(e);
      process.exit(1);
    });
}
